# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
jobs:
  test-and-report:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
    - name: Checkout to runner
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with unittest and generate coverage
      run: | 
        coverage run -m --source=mind unittest discover tests
        coverage xml -i
    - name: Override Coverage Source Path for Sonar
      run: |
        sudo apt update && sudo apt install tree
        tree /home /github
        sed -i "s/<source>\/home\/runner\/work\/mind\/mind<\/source>/<source>\/github\/workspace<\/source>/g" /github/workspace/coverage.xml
    - name: Analyze with SonarQube 
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
